# Generated by Django 6.0.7 on 2026-08-10 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_businesssettings_accent_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssettings",
            name="low_stock_alert",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="business_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for shop owners; staff point at the shop owner.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_active_staff",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="ShopPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=80)),
                ("can_view", models.BooleanField(default=True)),
                ("can_create", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["module"],
                "unique_together": {("owner", "module")},
            },
        ),
        migrations.CreateModel(
            name="ShopRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("owner", "name")},
            },
        ),
    ]
