# Generated by Django 6.0.7 on 2026-08-04 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("mobile", models.CharField(max_length=15)),
                ("business_name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True)),
                ("gst", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("overdue", "Overdue"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="customers/"),
                ),
                ("notes", models.TextField(blank=True)),
                ("last_transaction", models.DateField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["owner", "name"], name="customers_c_owner_i_0c182c_idx"
                    ),
                    models.Index(
                        fields=["owner", "mobile"],
                        name="customers_c_owner_i_fa5b24_idx",
                    ),
                    models.Index(
                        fields=["owner", "status"],
                        name="customers_c_owner_i_c3738a_idx",
                    ),
                ],
            },
        ),
    ]
