# Generated by Django 6.0.7 on 2026-08-21 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_groups",
                        to="companies.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("owner", "name")},
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("mobile", models.CharField(max_length=15)),
                ("business_name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True, default="")),
                ("billing_address", models.TextField(blank=True, default="")),
                ("shipping_address", models.TextField(blank=True, default="")),
                ("gst", models.CharField(blank=True, default="", max_length=20)),
                ("pan", models.CharField(blank=True, default="", max_length=10)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("state_code", models.CharField(blank=True, default="", max_length=2)),
                ("pincode", models.CharField(blank=True, default="", max_length=6)),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("credit_days", models.PositiveIntegerField(default=0)),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("overdue", "Overdue"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="customers/"),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("last_transaction", models.DateField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="companies.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers",
                        to="customers.customergroup",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["owner", "name"], name="customers_c_owner_i_0c182c_idx"
                    ),
                    models.Index(
                        fields=["owner", "mobile"],
                        name="customers_c_owner_i_fa5b24_idx",
                    ),
                    models.Index(
                        fields=["owner", "status"],
                        name="customers_c_owner_i_c3738a_idx",
                    ),
                    models.Index(
                        fields=["company", "name"],
                        name="customers_c_company_10527e_idx",
                    ),
                ],
            },
        ),
    ]
