# Generated by Django 6.0.7 on 2026-08-21 05:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("invoices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50)),
                (
                    "invoice_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("buyer_gstin", models.CharField(blank=True, max_length=15)),
                ("buyer_name", models.CharField(blank=True, max_length=200)),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("irn", models.CharField(blank=True, max_length=64)),
                ("ack_no", models.CharField(blank=True, max_length=40)),
                ("ack_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Generated", "Generated"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="e_invoices",
                        to="companies.company",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="e_invoices",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="e_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-invoice_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "status"],
                        name="gst_einvoic_company_8f8a87_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EWayBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_number", models.CharField(max_length=50)),
                (
                    "document_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("from_place", models.CharField(blank=True, max_length=120)),
                ("to_place", models.CharField(blank=True, max_length=120)),
                ("transporter_name", models.CharField(blank=True, max_length=200)),
                ("vehicle_no", models.CharField(blank=True, max_length=20)),
                ("distance_km", models.PositiveIntegerField(default=0)),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("ewb_number", models.CharField(blank=True, max_length=20)),
                ("valid_upto", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Active", "Active"),
                            ("Cancelled", "Cancelled"),
                            ("Expired", "Expired"),
                        ],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="e_way_bills",
                        to="companies.company",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="e_way_bills",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="e_way_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-document_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "status"],
                        name="gst_ewaybil_company_5d3162_idx",
                    )
                ],
            },
        ),
    ]
