# Generated by Django 6.0.7 on 2026-08-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_product_purchase_date"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="product",
            new_name="inventory_p_owner_i_698e17_idx",
            old_name="inventory_p_owner_i_7a2c1d_idx",
        ),
    ]
