# Generated by Django 6.0.7 on 2026-08-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0005_rename_inventory_p_owner_i_7a2c1d_idx_inventory_p_owner_i_698e17_idx",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="product",
            name="uniq_owner_sku_nonempty",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="inventory_p_owner_i_980359_idx",
        ),
        migrations.AddField(
            model_name="product",
            name="purchased_quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RemoveField(
            model_name="product",
            name="barcode",
        ),
        migrations.RemoveField(
            model_name="product",
            name="hsn",
        ),
        migrations.RemoveField(
            model_name="product",
            name="location",
        ),
        migrations.RemoveField(
            model_name="product",
            name="reorder_level",
        ),
        migrations.RemoveField(
            model_name="product",
            name="reorder_qty",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
    ]
