# Generated by Django 6.0.7 on 2026-08-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_remove_product_uniq_owner_sku_nonempty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="purchase_price_with_gst",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="product",
            name="selling_price_with_gst",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
