# Generated by Django 6.0.7 on 2026-08-11 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_product_price_with_gst_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["owner", "brand"], name="inventory_p_owner_i_d0429b_idx"
            ),
        ),
    ]
