# Generated by Django 6.0.7 on 2026-08-21 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary company of the shop owner (one per owner).",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("alias", models.CharField(blank=True, max_length=100)),
                ("gstin", models.CharField(blank=True, max_length=15)),
                ("pan", models.CharField(blank=True, max_length=10)),
                (
                    "registration_type",
                    models.CharField(default="Regular (With GST)", max_length=50),
                ),
                (
                    "party_type",
                    models.CharField(default="Not Applicable", max_length=50),
                ),
                ("gst_applicable_from", models.DateField(blank=True, null=True)),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                ("organization_type", models.CharField(blank=True, max_length=80)),
                ("business_type", models.CharField(blank=True, max_length=80)),
                ("industry_type", models.CharField(blank=True, max_length=80)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("country", models.CharField(default="India", max_length=80)),
                ("pincode", models.CharField(blank=True, max_length=12)),
                ("state", models.CharField(blank=True, max_length=80)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                ("fax", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("establish_date", models.DateField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                (
                    "signature",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_signatures/"
                    ),
                ),
                ("custom_fields", models.JSONField(blank=True, default=list)),
                (
                    "ownership",
                    models.CharField(
                        choices=[("own", "Own"), ("shared", "Shared")],
                        default="own",
                        max_length=20,
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Trial", "Trial"),
                            ("Expired", "Expired"),
                            ("Suspended", "Suspended"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for the logged-in user’s primary company; set for sub-companies.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_companies",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=20)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_years",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-label"],
            },
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["owner", "name"], name="companies_c_owner_i_7c157a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["owner", "gstin"], name="companies_c_owner_i_806ad5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["owner", "is_primary"], name="companies_c_owner_i_60ed61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["parent"], name="companies_c_parent__891875_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="company",
            unique_together={("owner", "name", "alias")},
        ),
        migrations.AddIndex(
            model_name="fiscalyear",
            index=models.Index(
                fields=["company", "label"], name="companies_f_company_82247d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fiscalyear",
            unique_together={("company", "label")},
        ),
    ]
