# Generated by Django 6.0.7 on 2026-08-21 05:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transporter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("vehicle_no", models.CharField(blank=True, max_length=40)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                ("gstin", models.CharField(blank=True, max_length=15)),
                ("status", models.CharField(default="Active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("formal_name", models.CharField(blank=True, max_length=80)),
                ("decimal_places", models.PositiveSmallIntegerField(default=2)),
                ("status", models.CharField(default="Active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("quotation", "Quotation"),
                            ("proforma", "Proforma Invoice"),
                            ("sales_order", "Sales Order"),
                            ("delivery_challan", "Delivery Challan"),
                            ("credit_note", "Credit Note"),
                            ("purchase_order", "Purchase Order"),
                            ("grn", "Goods Receipt"),
                            ("debit_note", "Debit Note"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("party", models.CharField(blank=True, max_length=200)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=18, max_digits=6),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "igst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("gst_type", models.CharField(default="GST", max_length=20)),
                ("place_of_supply", models.CharField(blank=True, max_length=80)),
                ("is_interstate", models.BooleanField(default=False)),
                ("status", models.CharField(default="Open", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("terms", models.TextField(blank=True)),
                ("fiscal_year", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoucherLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("hsn", models.CharField(blank=True, max_length=20)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=12),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=18, max_digits=6),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="AccountGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("Assets", "Assets"),
                            ("Liabilities", "Liabilities"),
                            ("Income", "Income"),
                            ("Expenses", "Expenses"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_system", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_groups",
                        to="companies.company",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="books.accountgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("account_number", models.CharField(blank=True, max_length=40)),
                ("ifsc", models.CharField(blank=True, max_length=20)),
                ("branch", models.CharField(blank=True, max_length=120)),
                (
                    "opening",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("status", models.CharField(default="Active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BankReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statement_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("bank", models.CharField(max_length=150)),
                (
                    "book_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "bank_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "difference",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("status", models.CharField(default="Pending", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciliations",
                        to="books.bankaccount",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_reconciliations",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-statement_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContraEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("from_account", models.CharField(max_length=150)),
                ("to_account", models.CharField(max_length=150)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("narration", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contra_entries",
                        to="companies.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contra_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.CharField(max_length=80)),
                ("prefix", models.CharField(max_length=30)),
                ("next_number", models.PositiveIntegerField(default=1)),
                ("fy", models.CharField(blank=True, max_length=20)),
                ("status", models.CharField(default="Active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_series",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["document"],
            },
        ),
        migrations.CreateModel(
            name="Godown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("address", models.TextField(blank=True)),
                ("in_charge", models.CharField(blank=True, max_length=120)),
                ("status", models.CharField(default="Active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="godowns",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HsnCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("type", models.CharField(default="HSN", max_length=10)),
                (
                    "gst_rate",
                    models.DecimalField(decimal_places=2, default=18, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hsn_codes",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ItemGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("status", models.CharField(default="Active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_groups",
                        to="companies.company",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="books.itemgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LedgerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("short_name", models.CharField(blank=True, max_length=50)),
                (
                    "opening",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("Dr", "Debit"), ("Cr", "Credit")],
                        default="Dr",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_accounts",
                        to="companies.company",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledgers",
                        to="books.accountgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("journal", "Journal"), ("gst", "GST Journal")],
                        default="journal",
                        max_length=20,
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("debit_account", models.CharField(blank=True, max_length=150)),
                ("credit_account", models.CharField(blank=True, max_length=150)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("type", models.CharField(blank=True, max_length=60)),
                ("narration", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="companies.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credit_ledger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_journals",
                        to="books.ledgeraccount",
                    ),
                ),
                (
                    "debit_ledger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="debit_journals",
                        to="books.ledgeraccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrintTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("document", models.CharField(max_length=80)),
                ("paper", models.CharField(default="A4", max_length=20)),
                ("copies", models.PositiveSmallIntegerField(default=1)),
                ("status", models.CharField(default="Active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_templates",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("item", models.CharField(blank=True, max_length=200)),
                ("from_godown", models.CharField(blank=True, max_length=120)),
                ("to_godown", models.CharField(blank=True, max_length=120)),
                (
                    "qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("narration", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_journals",
                        to="companies.company",
                    ),
                ),
                (
                    "destination_godown",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_in_journals",
                        to="books.godown",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_journals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
