# Generated by Django 6.0.7 on 2026-08-21 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        ("companies", "0001_initial"),
        ("customers", "0001_initial"),
        ("inventory", "0001_initial"),
        ("invoices", "0001_initial"),
        ("purchase", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stockjournal",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_journals",
                to="inventory.product",
            ),
        ),
        migrations.AddField(
            model_name="stockjournal",
            name="source_godown",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_out_journals",
                to="books.godown",
            ),
        ),
        migrations.AddField(
            model_name="transporter",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transporters",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vouchers",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vouchers",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vouchers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="related_bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_vouchers",
                to="purchase.purchasebill",
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="related_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_vouchers",
                to="invoices.invoice",
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="related_voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="books.voucher",
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vouchers",
                to="inventory.supplier",
            ),
        ),
        migrations.AddField(
            model_name="voucherline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voucher_lines",
                to="inventory.product",
            ),
        ),
        migrations.AddField(
            model_name="voucherline",
            name="voucher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="books.voucher",
            ),
        ),
        migrations.AddIndex(
            model_name="accountgroup",
            index=models.Index(
                fields=["company", "nature"], name="books_accou_company_139ac2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accountgroup",
            unique_together={("company", "name", "parent")},
        ),
        migrations.AlterUniqueTogether(
            name="bankaccount",
            unique_together={("company", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="contraentry",
            unique_together={("company", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="documentseries",
            unique_together={("company", "document", "fy")},
        ),
        migrations.AlterUniqueTogether(
            name="godown",
            unique_together={("company", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="hsncode",
            unique_together={("company", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="itemgroup",
            unique_together={("company", "name")},
        ),
        migrations.AddIndex(
            model_name="ledgeraccount",
            index=models.Index(
                fields=["company", "status"], name="books_ledge_company_8f8199_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ledgeraccount",
            unique_together={("company", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="journalentry",
            unique_together={("company", "kind", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="printtemplate",
            unique_together={("company", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="stockjournal",
            unique_together={("company", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="unit",
            unique_together={("company", "name")},
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(
                fields=["company", "doc_type", "date"],
                name="books_vouch_company_e40335_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(
                fields=["company", "status"], name="books_vouch_company_162004_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="voucher",
            unique_together={("company", "doc_type", "number")},
        ),
    ]
